CREATE TABLE IF NOT EXISTS readings (
  id SERIAL PRIMARY KEY,
  total_power_w DOUBLE PRECISION NOT NULL,
  temperature_c DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS appliances (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  power_w DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS energy_logs (
  id SERIAL PRIMARY KEY,
  kwh DOUBLE PRECISION NOT NULL,
  cost DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

INSERT INTO settings (key, value)
VALUES ('prepaid_mode', 'on')
ON CONFLICT (key) DO NOTHING;
